### ISSUE TITLE
OctoberCMS (Laravel 5.5 based) support

### ISSUE THREAD

**Issue by tamer-hassan** [swooletw/laravel-swoole#129]
1. Please provide your PHP and Swoole version. (`php -v` and `php --ri swoole`)

```
# php --version
PHP 7.1.12 (cli) (built: Dec 12 2017 06:20:32) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.1.12, Copyright (c) 1999-2017, by Zend Technologies
    with blackfire v1.22.0~linux-x64-non_zts71, https://blackfire.io, by Blackfire

# php --ri swoole

swoole

swoole support => enabled
Version => 4.0.4
Author => Swoole Group[email: team@swoole.com]
coroutine => enabled
epoll => enabled
eventfd => enabled
signalfd => enabled
cpu affinity => enabled
spinlock => enabled
rwlock => enabled
async http/websocket client => enabled
zlib => enabled
mutex_timedlock => enabled
pthread_barrier => enabled
futex => enabled

Directive => Local Value => Master Value
swoole.aio_thread_num => 2 => 2
swoole.display_errors => On => On
swoole.use_namespace => On => On
swoole.use_shortname => On => On
swoole.fast_serialize => Off => Off
swoole.unixsock_buffer_size => 8388608 => 8388608

```

2. Please provide your Laravel/Lumen version.

OctoberCMS (Laravel 5.5 based)

https://octobercms.com/
https://github.com/octobercms

3. Which release version of this package are you using?

"swooletw/laravel-swoole": "^2.0"

4. What did you do? If possible, provide a recipe for reproducing the error.

- Add `SwooleTW\Http\LaravelServiceProvider` to the list of Providers in config/app.php
- Run `php artisan swoole:http start`

5. What did you expect to see?

A running Swoole HTTP Server.

6. What did you see instead?

Infinite loop error until CTRL+C is pressed:

```
root@5056bae33839:/var/www/internal-october# php artisan swoole:http start
Starting swoole http server...
Swoole http server started: <http://127.0.0.1:1215>
PHP Fatal error:  Uncaught TypeError: Argument 2 passed to Illuminate\Routing\UrlGenerator::__construct() must be an instance of Illuminate\Http\Request, null given, called in /var/www/internal-october/vendor/laravel/framework/src/Illuminate/Routing/RoutingServiceProvider.php on line 67 and defined in /var/www/internal-october/vendor/laravel/framework/src/Illuminate/Routing/UrlGenerator.php:102
Stack trace:
#0 /var/www/internal-october/vendor/laravel/framework/src/Illuminate/Routing/RoutingServiceProvider.php(67): Illuminate\Routing\UrlGenerator->__construct(Object(Illuminate\Routing\RouteCollection), NULL)
#1 /var/www/internal-october/vendor/laravel/framework/src/Illuminate/Container/Container.php(749): Illuminate\Routing\RoutingServiceProvider->Illuminate\Routing\{closure}(Object(October\Rain\Foundation\Application), Array)
#2 /var/www/internal-october/vendor/laravel/framework/src/Illuminate/Container/Container.php(631): Illuminate\Container\Container->build(Object(Closure))
#3 /var/www/internal-october/vendor/laravel/framew in /var/www/internal-october/vendor/laravel/framework/src/Illuminate/Routing/UrlGenerator.php on line 102
PHP Fatal error:  Uncaught TypeError: Argument 2 passed to Illuminate\Routing\UrlGenerator::__construct() must be an instance of Illuminate\Http\Request, null given, called in /var/www/internal-october/vendor/laravel/framework/src/Illuminate/Routing/RoutingServiceProvider.php on line 67 and defined in /var/www/internal-october/vendor/laravel/framework/src/Illuminate/Routing/UrlGenerator.php:102
Stack trace:
#0 /var/www/internal-october/vendor/laravel/framework/src/Illuminate/Routing/RoutingServiceProvider.php(67): Illuminate\Routing\UrlGenerator->__construct(Object(Illuminate\Routing\RouteCollection), NULL)
#1 /var/www/internal-october/vendor/laravel/framework/src/Illuminate/Container/Container.php(749): Illuminate\Routing\RoutingServiceProvider->Illuminate\Routing\{closure}(Object(October\Rain\Foundation\Application), Array)
#2 /var/www/internal-october/vendor/laravel/framework/src/Illuminate/Container/Container.php(631): Illuminate\Container\Container->build(Object(Closure))
#3 /var/www/internal-october/vendor/laravel/framew in /var/www/internal-october/vendor/laravel/framework/src/Illuminate/Routing/UrlGenerator.php on line 102
[..snip..]
```

**Comment by albertcht** [comment]
Hi @tamer-hassan ,

OctoborCMS is a highly customized Laravel project. This package won't support it.
