### ISSUE TITLE
Error while reading line from the server

### ISSUE THREAD

**Issue by Honvid** [swooletw/laravel-swoole#134]
Make sure you read **Issues Guideline** and answer these questions before submitting your issue. Thanks!
(Any **non-English** issues will be closed immediately.)

1. Please provide your PHP and Swoole version. (`php -v` and `php --ri swoole`)

PHP version

```
PHP 7.1.7 (cli) (built: Jul 15 2017 18:08:09) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies
    with Xdebug v2.7.0alpha2-dev, Copyright (c) 2002-2018, by Derick Rethans
```
swoole info:

```
swoole

swoole support => enabled
Version => 1.10.5
Author => tianfeng.han[email: mikan.tenny@gmail.com]
kqueue => enabled
rwlock => enabled
async http/websocket client => enabled
pcre => enabled
zlib => enabled

Directive => Local Value => Master Value
swoole.aio_thread_num => 2 => 2
swoole.display_errors => On => On
swoole.use_namespace => Off => Off
swoole.fast_serialize => Off => Off
swoole.unixsock_buffer_size => 8388608 => 8388608

```

2. Please provide your Laravel/Lumen version.

Laravel  version 5.4

3. Which release version of this package are you using?

`"swooletw/laravel-swoole": "^2.3"`

4. What did you do? If possible, provide a recipe for reproducing the error.

i've used this package for check user's login status by the websocket. 

first, I use the `table` driver. it show the error 

`ErrorException: Swoole\Table::set(): unable to allocate memory`

i found that it because the memory set, and then i found can change `table` driver to `redis`. so change it.

now it have error looks like bellow:
_______________
[2018-08-31 15:35:30]   046cebaf74              artisan/swoole:http/start  Predis\Connection\ConnectionException: Error while reading line from the server. [tcp://mongodb-01:26379] in /app/path/vendor/predis/predis/src/Connection/AbstractConnection.php:155\nStack trace:\n#0 /app/path/vendor/predis/predis/src/Connection/StreamConnection.php(314): Predis\Connection\AbstractConnection->onConnectionError('Error while rea...')\n#1 /app/path/vendor/predis/predis/src/Connection/AbstractConnection.php(120): Predis\Connection\StreamConnection->read()\n#2 /app/path/vendor/predis/predis/src/Connection/AbstractConnection.php(112): Predis\Connection\AbstractConnection->readResponse(Object(Predis\Command\SetMembers))\n#3 /app/path/vendor/predis/predis/src/Client.php(331): Predis\Connection\AbstractConnection->executeCommand(Object(Predis\Command\SetMembers))\n#4 /app/path/vendor/predis/predis/src/Client.php(314): Predis\Client->executeCommand(Object(Predis\Command\SetMembers))\n#5 /app/path/vendor/swooletw/laravel-swoole/src/Websocket/Rooms/RedisRoom.php(138): Predis\Client->__call('smembers', Array)\n#6 /app/path/vendor/swooletw/laravel-swoole/src/Websocket/Rooms/RedisRoom.php(124): SwooleTW\Http\Websocket\Rooms\RedisRoom->getValue('112', 'fds')\n#7 /app/path/vendor/swooletw/laravel-swoole/src/Websocket/Rooms/RedisRoom.php(80): SwooleTW\Http\Websocket\Rooms\RedisRoom->getRooms(112)\n#8 /app/path/vendor/swooletw/laravel-swoole/src/Websocket/Websocket.php(136): SwooleTW\Http\Websocket\Rooms\RedisRoom->delete(112, Array)\n#9 /app/path/vendor/swooletw/laravel-swoole/src/Websocket/CanWebsocket.php(145): SwooleTW\Http\Websocket\Websocket->leave()\n#10 {main}  1596.4250481129
_______________

i found that issue from `predis`[url](https://github.com/nrk/predis/issues/507), it should add option as `read_write_timeout = -1`, can this is ok?

5. What did you expect to see?

it works fine.

6. What did you see instead?

error.

**Comment by albertcht** [comment]
Hi @Honvid ,

1. `ErrorException: Swoole\Table::set(): unable to allocate memory` this message shows when your server doesn't have enough memory space to allocate.
2. Try to set `read_write_timeout = 0` to avoid timeout.

**Comment by shenglin-php** [comment]
> 
> 
> Hi @Honvid ,
> 
>     1. `ErrorException: Swoole\Table::set(): unable to allocate memory` this message shows when your server doesn't have enough memory space to allocate.
> 
>     2. Try to set `read_write_timeout = 0` to avoid timeout.

PHP 7.3.11 (cli) (built: Dec 20 2019 14:06:10) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.11, Copyright (c) 1998-2018 Zend Technologies


+-----------------+------------------------------------------------+
| Name            | Value                                          |
+-----------------+------------------------------------------------+
| PHP Version     | 7.3.11                                         |
| Swoole Version  | 4.4.13                                         |
| Laravel Version | 6.6.2                                          |
| Listen IP       | 0.0.0.0                                        |
| Listen Port     | 1215                                           |
| Server Status   | Online                                         |
| Reactor Num     | 4                                              |
| Worker Num      | 50                                             |
| Task Worker Num | 2                                              |
| Websocket Mode  | On                                             |
| Master PID      | 1273                                           |
| Manager PID     | 1274                                           |
| Log Path        | /home/wwwroot/udj/storage/logs/swoole_http.log |
+-----------------+------------------------------------------------+
 
Laravel 6.*

**Comment by shenglin-php** [comment]
> 
> 
> Hi @Honvid ,
> 
>     1. `ErrorException: Swoole\Table::set(): unable to allocate memory` this message shows when your server doesn't have enough memory space to allocate.
> 
>     2. Try to set `read_write_timeout = 0` to avoid timeout.

PHP 7.3.11 (cli) (built: Dec 20 2019 14:06:10) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.11, Copyright (c) 1998-2018 Zend Technologies

+-----------------+------------------------------------------------+
| Name | Value |
+-----------------+------------------------------------------------+
| PHP Version | 7.3.11 |
| Swoole Version | 4.4.13 |
| Laravel Version | 6.6.2 |
| Listen IP | 0.0.0.0 |
| Listen Port | 1215 |
| Server Status | Online |
| Reactor Num | 4 |
| Worker Num | 50 |
| Task Worker Num | 2 |
| Websocket Mode | On |
| Master PID | 1273 |
| Manager PID | 1274 |
| Log Path | /home/wwwroot/udj/storage/logs/swoole_http.log |
+-----------------+------------------------------------------------+

Laravel 6.*

"swooletw/laravel-swoole": "^2.6"

Server Redis Version 2.8  default timeout = 0 

It also happened
