### ISSUE TITLE
ExceptionHandler::report() mu st be an instance of Exception

### ISSUE THREAD

**Issue by senbai** [swooletw/laravel-swoole#153]
Hey There
i got This error after start the **swoole** server  in the command line with artisan
```

In ExceptionHandler.php line 58:                                                                                                                                                           
  Uncaught TypeError: Argument 1 passed to NunoMaduro\Collision\Adapters\Laravel\ExceptionHandler::report() must be an instance of Exception, instance of TypeError gi  
  ven, called in /opt/lampp/htdocs/swoole/vendor/swooletw/laravel-swoole/src/Server/Manager.php on line 388 and defined in /opt/lampp/htdocs/swoole/vendor/nunomaduro/  
  collision/src/Adapters/Laravel/ExceptionHandler.php:58                                                                                                                
  Stack trace:                                                                                                                                                          
  #0 /opt/lampp/htdocs/swoole/vendor/swooletw/laravel-swoole/src/Server/Manager.php(388): NunoMaduro\Collision\Adapters\Laravel\ExceptionHandler->report(Object(TypeEr  
  ror))                                                                                                                                                                 
  #1 /opt/lampp/htdocs/swoole/vendor/swooletw/laravel-swoole/src/Concerns/InteractsWithWebsocket.php(67): SwooleTW\Http\Server\Manager->logServerError(Object(TypeErro  
  r))                                                                                                                                                                   
  #2 {main}                                                                                                                                                             
    thrown                                                                                                                                                              
             

```

php version 7.2.10
swoole version 4.2.3
laravel version 5.7

any solution please :(

**Comment by albertcht** [comment]
Hi @senbai,

Thanks for your report, can you try the latest develop branch? It should be fixed in this commit: [f3cb2f9f](https://github.com/swooletw/laravel-swoole/commit/f3cb2f9fbff7830d3c4a17b14bc4eae79e96f639).
