### ISSUE TITLE
Problem resolving swoole.websocket or swoole.sandbox

### ISSUE THREAD

**Issue by prolic** [swooletw/laravel-swoole#159]
PHP: 7.2.11
Swoole: 4.2.5
Laravel: 5.6
Laravel-Swoole: 2.5

When trying to use a go-routine with and async call inside, the website doesn't respond and I have the following in the logs:

```
In Container.php line 767:
                                                                               
  Uncaught ReflectionException: Class swoole.websocket does not exist in /var  
  /www/vendor/laravel/framework/src/Illuminate/Container/Container.php:767     
  Stack trace:                                                                 
  #0 /var/www/vendor/laravel/framework/src/Illuminate/Container/Container.php  
  (767): ReflectionClass->__construct('swoole.websocke...')                    
  #1 /var/www/vendor/laravel/framework/src/Illuminate/Container/Container.php  
  (646): Illuminate\Container\Container->build('swoole.websocke...')           
  #2 /var/www/vendor/laravel/framework/src/Illuminate/Container/Container.php  
  (601): Illuminate\Container\Container->resolve('swoole.websocke...', Array)  
  #3 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Application.  
  php(734): Illuminate\Container\Container->make('swoole.websocke...', Array)  
  #4 /var/www/vendor/laravel/framework/src/Illuminate/Container/Container.php  
  (1210): Illuminate\Foundation\Application->make('swoole.websocke...')        
  #5 /var/www/vendor/swooletw/laravel-swoole/src/Server/Manager.php(220): Ill  
  uminate\Container\Container->offsetGet('swoole.websocke...')                 
```

After setting SWOOLE_HTTP_WEBSOCKET to false, this error is gone and instead another one pops up:

```
In Container.php line 767:
                                                                               
  Uncaught ReflectionException: Class swoole.sandbox does not exist in /var/w  
  ww/vendor/laravel/framework/src/Illuminate/Container/Container.php:767       
  Stack trace:                                                                 
  #0 /var/www/vendor/laravel/framework/src/Illuminate/Container/Container.php  
  (767): ReflectionClass->__construct('swoole.sandbox')                        
  #1 /var/www/vendor/laravel/framework/src/Illuminate/Container/Container.php  
  (646): Illuminate\Container\Container->build('swoole.sandbox')               
  #2 /var/www/vendor/laravel/framework/src/Illuminate/Container/Container.php  
  (601): Illuminate\Container\Container->resolve('swoole.sandbox', Array)      
  #3 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Application.  
  php(734): Illuminate\Container\Container->make('swoole.sandbox', Array)      
  #4 /var/www/vendor/laravel/framework/src/Illuminate/Container/Container.php  
  (1210): Illuminate\Foundation\Application->make('swoole.sandbox')            
  #5 /var/www/vendor/swooletw/laravel-swoole/src/Server/Manager.php(209): Ill  
  uminate\Container\Container->offsetGet('swoole.sandbox')     
```

Am I doing something wrong?

**Comment by prolic** [comment]
Still not knowing what's wrong, but I did something differently and the problem is gone.
