### ISSUE TITLE
Invalid table name.

### ISSUE THREAD

**Issue by noecs** [swooletw/laravel-swoole#202]
1.Local environment：
```
PHP Version     7.2.8                                                                          
Swoole Version  4.2.10                                                                          
Laravel Version 5.5.44                                                                          
Listen IP       127.0.0.1                                                                       
Listen Port     5200                                                                            
Server Status   Online                                                                          
Reactor Num     6                                                                               
Worker Num       6                                                                               
Task Worker Num 6                                                                               
Websocket Mode  On                                                                              
PID             1951                                                                            
Log Path         /Users/noecs/Desktop/noecs-system/noecs-system-php/storage/logs/swoole_http.log
```
2.composer.json
```
"require": {
        "php": ">=7.0.0",
        "dingo/api": "2.0.0-alpha1",
        "fideloper/proxy": "~3.3",
        "gregwar/captcha": "dev-master",
        "laravel/framework": "5.5.*",
        "laravel/passport": "~4.0",
        "laravel/tinker": "~1.0",
        "liyu/dingo-serializer-switch": "dev-master",
        "paragonie/random_compat": "^2.0",
        "predis/predis": "v1.1.x-dev",
        "swooletw/laravel-swoole": "dev-master"
    },
    "require-dev": {
        "eaglewu/swoole-ide-helper": "dev-master",
        "filp/whoops": "~2.0",
        "fzaninotto/faker": "~1.4",
        "mockery/mockery": "~1.0",
        "phpunit/phpunit": "~6.0",
        "symfony/thanks": "^1.0"
    }
``` 
3.my question:Sorry to bother you again. I am using `Websocket::loginUsing($user);`, something went wrong, the error stack
```
[2019-01-29 13:04:19] local.ERROR: Invalid table name. {"exception":"[object] (InvalidArgumentException(code: 0): Invalid table name. at /Users/noecs/Desktop/noecs-system/noecs-system-php/vendor/swooletw/laravel-swoole/src/Websocket/Rooms/TableRoom.php:210)
[stacktrace]
#0 /Users/noecs/Desktop/noecs-system/noecs-system-php/vendor/swooletw/laravel-swoole/src/Websocket/Rooms/TableRoom.php(195): SwooleTW\\Http\\Websocket\\Rooms\\TableRoom->checkTable('fds')
#1 /Users/noecs/Desktop/noecs-system/noecs-system-php/vendor/swooletw/laravel-swoole/src/Websocket/Rooms/TableRoom.php(122): SwooleTW\\Http\\Websocket\\Rooms\\TableRoom->getValue('1', 'fds')
#2 /Users/noecs/Desktop/noecs-system/noecs-system-php/vendor/swooletw/laravel-swoole/src/Websocket/Rooms/TableRoom.php(55): SwooleTW\\Http\\Websocket\\Rooms\\TableRoom->getRooms(1)
#3 /Users/noecs/Desktop/noecs-system/noecs-system-php/vendor/swooletw/laravel-swoole/src/Websocket/Websocket.php(134): SwooleTW\\Http\\Websocket\\Rooms\\TableRoom->add(1, Array)
#4 /Users/noecs/Desktop/noecs-system/noecs-system-php/vendor/swooletw/laravel-swoole/src/Websocket/Authenticatable.php(38): SwooleTW\\Http\\Websocket\\Websocket->join(Array)
#5 /Users/noecs/Desktop/noecs-system/noecs-system-php/vendor/swooletw/laravel-swoole/src/Websocket/Authenticatable.php(26): SwooleTW\\Http\\Websocket\\Websocket->loginUsingId(1)
#6 /Users/noecs/Desktop/noecs-system/noecs-system-php/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(221): SwooleTW\\Http\\Websocket\\Websocket->loginUsing(Object(App\\Models\\User))
#7 /Users/noecs/Desktop/noecs-system/noecs-system-php/app/Http/Controllers/Admin/Api/Chat/ListController.php(15): Illuminate\\Support\\Facades\\Facade::__callStatic('loginUsing', Array)
#8 [internal function]: App\\Http\\Controllers\\Admin\\Api\\Chat\\ListController->send(Object(Illuminate\\Http\\Request), Object(SwooleTW\\Http\\Websocket\\Websocket))
#9 /Users/noecs/Desktop/noecs-system/noecs-system-php/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Array, Array)
#10 /Users/noecs/Desktop/noecs-system/noecs-system-php/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#11 /Users/noecs/Desktop/noecs-system/noecs-system-php/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#12 /Users/noecs/Desktop/noecs-system/noecs-system-php/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(60): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array)
#13 /Users/noecs/Desktop/noecs-system/noecs-system-php/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(24): Illuminate\\Container\\BoundMethod::callClass(Object(Illuminate\\Foundation\\Application), '\\\\App\\\\Http\\\\Contr...', Array, NULL)
#14 /Users/noecs/Desktop/noecs-system/noecs-system-php/vendor/laravel/framework/src/Illuminate/Container/Container.php(549): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), '\\\\App\\\\Http\\\\Contr...', Array, NULL)
#15 /Users/noecs/Desktop/noecs-system/noecs-system-php/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(221): Illuminate\\Container\\Container->call('\\\\App\\\\Http\\\\Contr...', Array)
#16 /Users/noecs/Desktop/noecs-system/noecs-system-php/vendor/swooletw/laravel-swoole/src/Websocket/Websocket.php(264): Illuminate\\Support\\Facades\\Facade::__callStatic('call', Array)
#17 /Users/noecs/Desktop/noecs-system/noecs-system-php/vendor/swooletw/laravel-swoole/src/Concerns/InteractsWithWebsocket.php(76): SwooleTW\\Http\\Websocket\\Websocket->call('connect', Object(Illuminate\\Http\\Request))
#18 {main}
"} 
```
I read the documentation and issuse repeatedly and didn't mention similar issues. I tried to `construct` print `$room` in `/vendor/swooletw/laravel-swoole/src/Websocket/websocket.php` and I got a lot of null attributes.

**Comment by albertcht** [comment]
This bug has been fixed in the new release `v.2.6.3`.

**Comment by noecs** [comment]
Thank you for your help, I am testing now.
