### ISSUE TITLE
deployment problem with apache or nginx 

### ISSUE THREAD

**Issue by mRamadan0101** [swooletw/laravel-swoole#394]
Make sure you read **Issues Guideline** and answer these questions before submitting your issue. Thanks!
(Any **non-English** issues will be closed immediately.)

1. Please provide your PHP and Swoole version. (`php -v` and `php --ri swoole`)
php 7.2

2. Please provide your Laravel/Lumen version.
laravel 6

3. Which release version of this package are you using?
"swooletw/laravel-swoole": "^2.6"

4. What did you do? If possible, provide a recipe for reproducing the error.
i deplooy my project to apache server and run start command and its **not working** 
install nginx server and run start command its work but i got this error
```
Firefox can’t establish a connection to the server at ws://192.168.1.154:1215/socket.io/?EIO=3&transport=websocket. socket.io.js:8:6159
The connection to ws://192.168.1.154:1215/socket.io/?EIO=3&transport=websocket was interrupted while the page was loading.
```
and can not connect socket

5. What did you expect to see?
everything working fine

6. What did you see instead?
```
Firefox can’t establish a connection to the server at ws://192.168.1.154:1215/socket.io/?EIO=3&transport=websocket. socket.io.js:8:6159
The connection to ws://192.168.1.154:1215/socket.io/?EIO=3&transport=websocket was interrupted while the page was loading.
```

**Comment by mRamadan0101** [comment]
fixed with amazon service
