### ISSUE TITLE
Symfony\Component\Debug\Exception\FatalThrowableError class not found

### ISSUE THREAD

**Issue by ddzobov** [swooletw/laravel-swoole#406]
Lumen 7.1.2

**Comment by mRamadan0101** [comment]
when u see this error message?

**Comment by Lardpower** [comment]
I have absolutely the same error:

```
[2020-05-16 21:43:56] local.ERROR: Uncaught Error: Class 'Symfony\Component\Debug\Exception\FatalThrowableError' not found in website/vendor/swooletw/laravel-swoole/src/Server/Manager.php:414
Stack trace:
#0 website/vendor/swooletw/laravel-swoole/src/Server/Manager.php(398): SwooleTW\Http\Server\Manager->normalizeException()
#1 website/vendor/swooletw/laravel-swoole/src/Concerns/InteractsWithWebsocket.php(105): SwooleTW\Http\Server\Manager->logServerError()
#2 {main}
  thrown {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Uncaught Error: Class 'Symfony\\Component\\Debug\\Exception\\FatalThrowableError' not found in website/vendor/swooletw/laravel-swoole/src/Server/Manager.php:414
Stack trace:
#0 website/vendor/swooletw/laravel-swoole/src/Server/Manager.php(398): SwooleTW\\Http\\Server\\Manager->normalizeException()
#1 website/vendor/swooletw/laravel-swoole/src/Concerns/InteractsWithWebsocket.php(105): SwooleTW\\Http\\Server\\Manager->logServerError()
#2 {main}
  thrown at website/vendor/swooletw/laravel-swoole/src/Server/Manager.php:414)
[stacktrace]
#0 {main}
"} 
```

My `composer.json` file:
```
{
...
    "require": {
        "php": "^7.4",
        "fideloper/proxy": "^4.2",
        "fruitcake/laravel-cors": "^1.0",
        "guzzlehttp/guzzle": "^6.3",
        "laravel/framework": "^7.0",
        "laravel/tinker": "^2.0",
        "swooletw/laravel-swoole": "^2.6"
    },
    "require-dev": {
        "facade/ignition": "^2.0",
        "fzaninotto/faker": "^1.9.1",
        "mockery/mockery": "^1.3.1",
        "nunomaduro/collision": "^4.1",
        "phpunit/phpunit": "^8.5"
    }
...
}
```



I had to add `symfony/debug": "^4",` into my `composer.json` to start see the problem with my code (the "real" debug data). I believe it is not related to the current issue, but just in case here's the problem:

```
Symfony\Component\Debug\Exception\FatalThrowableError: Argument 2 passed to application\messaging\controllers\ConnectionController::onConnect() must be an instance of Illuminate\Http\Client\Request, instance of Illuminate\Http\Request given
```

Thanks!

**Comment by Lardpower** [comment]
I have absolutely the same error:

```
[2020-05-16 21:43:56] local.ERROR: Uncaught Error: Class 'Symfony\Component\Debug\Exception\FatalThrowableError' not found in website/vendor/swooletw/laravel-swoole/src/Server/Manager.php:414
Stack trace:
#0 website/vendor/swooletw/laravel-swoole/src/Server/Manager.php(398): SwooleTW\Http\Server\Manager->normalizeException()
#1 website/vendor/swooletw/laravel-swoole/src/Concerns/InteractsWithWebsocket.php(105): SwooleTW\Http\Server\Manager->logServerError()
#2 {main}
  thrown {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Uncaught Error: Class 'Symfony\\Component\\Debug\\Exception\\FatalThrowableError' not found in website/vendor/swooletw/laravel-swoole/src/Server/Manager.php:414
Stack trace:
#0 website/vendor/swooletw/laravel-swoole/src/Server/Manager.php(398): SwooleTW\\Http\\Server\\Manager->normalizeException()
#1 website/vendor/swooletw/laravel-swoole/src/Concerns/InteractsWithWebsocket.php(105): SwooleTW\\Http\\Server\\Manager->logServerError()
#2 {main}
  thrown at website/vendor/swooletw/laravel-swoole/src/Server/Manager.php:414)
[stacktrace]
#0 {main}
"} 
```

My `composer.json` file:
```
{
...
    "require": {
        "php": "^7.4",
        "fideloper/proxy": "^4.2",
        "fruitcake/laravel-cors": "^1.0",
        "guzzlehttp/guzzle": "^6.3",
        "laravel/framework": "^7.0",
        "laravel/tinker": "^2.0",
        "swooletw/laravel-swoole": "^2.6"
    },
    "require-dev": {
        "facade/ignition": "^2.0",
        "fzaninotto/faker": "^1.9.1",
        "mockery/mockery": "^1.3.1",
        "nunomaduro/collision": "^4.1",
        "phpunit/phpunit": "^8.5"
    }
...
}
```



I had to add `symfony/debug": "^4",` into my `composer.json` to start see the problem with my code (the "real" debug data). I believe it is not related to the current issue, but just in case here's the problem:

```
Symfony\Component\Debug\Exception\FatalThrowableError: Argument 2 passed to App\Http\Controllers\Controller::onConnect() must be an instance of Illuminate\Http\Client\Request, instance of Illuminate\Http\Request given
```

Thanks!

**Comment by netdown** [comment]
#417 fixes this.

**Comment by Lardpower** [comment]
Thank you.
